# Generated by Django 4.2.13 on 2024-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("guest_number", models.IntegerField()),
                ("comment", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("Id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("description", models.TextField(max_length=1000)),
                ("inventory", models.IntegerField()),
            ],
        ),
    ]
